version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: registry.gitlab.com/milon27/gql-ecom-server
    restart: always
    ports:
      - 4000:4000
