name: Docker CI CD 2

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout all code
        uses: actions/checkout@v3

      - name: Set Output
        run: echo "MY_TEST=hello1234" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: get Output
        env:
          OUTPUT1: ${{needs.build.outputs.output1}}
          OUTPUT2: ${{needs.build.outputs.MY_TEST}}
        run: echo "hey, $OUTPUT1, $OUTPUT2"
