name: Docker CI CD 2

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Output
        id: set-output
        run: |
          echo "::set-output name=myTest::hello1234"
    outputs:
      myTest: ${{ steps.set-output.outputs.myTest }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: get Output
        run: echo "hey, ${{ needs.build.outputs.myTest }}"
